basePath: /
definitions:
  ads.AdRequest:
    properties:
      AirplaneModel:
        type: string
      Category:
        type: string
      Description:
        type: string
      ExpertCheck:
        type: boolean
      FlyTime:
        type: integer
      Image:
        type: string
      PlaneAge:
        type: integer
      Price:
        type: integer
      RepairCheck:
        type: boolean
      Subject:
        type: string
    type: object
  ads.AdResponse:
    properties:
      AirplaneModel:
        type: string
      CategoryID:
        type: integer
      Description:
        type: string
      ExpertCheck:
        type: boolean
      FlyTime:
        type: integer
      ID:
        type: integer
      Image:
        type: string
      PlaneAge:
        type: integer
      Price:
        type: integer
      RepairCheck:
        type: boolean
      Status:
        type: string
      Subject:
        type: string
      UserID:
        type: integer
    type: object
  ads.ErrorAddAd:
    properties:
      message:
        type: string
      responsecode:
        type: integer
    type: object
  models.Ad:
    properties:
      airplaneModel:
        type: string
      category:
        $ref: '#/definitions/models.Category'
      categoryID:
        type: integer
      description:
        type: string
      expertCheck:
        type: boolean
      flyTime:
        type: integer
      id:
        type: integer
      image:
        type: string
      planeAge:
        type: integer
      price:
        type: integer
      repairCheck:
        type: boolean
      status:
        type: string
      subject:
        type: string
      user:
        $ref: '#/definitions/models.User'
      userID:
        type: integer
    type: object
  models.Bookmarks:
    properties:
      ads:
        $ref: '#/definitions/models.Ad'
      adsID:
        type: integer
      user:
        $ref: '#/definitions/models.User'
      userID:
        type: integer
    type: object
  models.Category:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.User:
    properties:
      bookmarks:
        items:
          $ref: '#/definitions/models.Bookmarks'
        type: array
      id:
        type: integer
      password:
        type: string
      role:
        type: integer
      username:
  handlers.AmountFee:
    properties:
      fee:
        type: integer
    type: object
  handlers.ErrorResponseRegisterLogin:
    properties:
      message:
        type: string
      responsecode:
        type: integer
    type: object
  handlers.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  handlers.RequestResponse:
    properties:
      payment_url:
        type: string
    type: object
  handlers.UserCreateRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  handlers.UserResponse:
    properties:
      ID:
        type: integer
      IsActive:
        type: boolean
      Password:
        type: string
      Token:
        type: string
      UserID:
        type: integer
      Username:
        type: string
    type: object
  handlers.VerifyResponse:
    properties:
      Authority:
        type: string
      Status:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Quera Airplane-Divar server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Airplane-Divar
  version: "1.0"
paths:
  /ads:
    get:
      consumes:
      - application/json
      description: Retrieves ads from database and accept query params.
  /users/login:
    post:
      consumes:
      - application/json
      description: Login with username and password
      parameters:
      - description: Login request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Ad'
            type: array
        "500":
          description: Could not retrieve ads
          schema:
            type: string
      summary: List of ads.
      tags:
      - ads
  /ads/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves an ad based on the provided ID
      parameters:
      - description: Ad ID
        in: query
        name: id
        required: true
        type: integer
            $ref: '#/definitions/handlers.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponseRegisterLogin'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handlers.ErrorResponseRegisterLogin'
      summary: User login
      tags:
      - users
  /users/payment/request:
    post:
      consumes:
      - application/json
      description: Zarinpal Payment to add budget to user
      parameters:
      - description: Payment request details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.AmountFee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.RequestResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Add budget request
      tags:
      - payment
  /users/payment/verify:
    get:
      consumes:
      - application/json
      description: Verify Zarinpal Payment to add budget to user
      parameters:
      - description: Payment verify details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.VerifyResponse'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Ad'
        "400":
          description: Invalid parameter id
          schema:
            type: string
        "500":
          description: Could not retrieve ads
          schema:
            type: string
      summary: Get ad by ID
      tags:
      - ads
  /ads/add:
    post:
      consumes:
      - application/json
      description: Create new ad by given properties
      parameters:
      - description: Ad details
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Verify budget payment and add budget
      tags:
      - payment
  /users/register:
    post:
      consumes:
      - application/json
      description: Register a new user with the provided information
      parameters:
      - description: User registration details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/ads.AdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ads.AdResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/ads.ErrorAddAd'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ads.ErrorAddAd'
      summary: Create an ad
      tags:
      - ads
          $ref: '#/definitions/handlers.UserCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponseRegisterLogin'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handlers.ErrorResponseRegisterLogin'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponseRegisterLogin'
      summary: Register a new user
      tags:
      - users
swagger: "2.0"
